In [6]:
import pandas as pd
import numpy as np
from typing import List, Tuple
from datetime import datetime
from collections import Counter

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from pymongo import MongoClient
from pymongo.server_api import ServerApi
import requests
import json
import time

In [3]:
path = r"C:\Users\dell\Desktop\movie_tv_data\tmdb-movie-tv-data-analysis\data\netflix_titles.csv"
df = pd.read_csv(path)

df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [13]:
import requests

url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyZDM3YWE2YjNkZDI3MDMyNzZhODc5Yzk5ZmYwZThmYSIsIm5iZiI6MTc4ODQyMDI1OS4xNzI5OTk5LCJzdWIiOiI2YTk5MjBhM2JkOTk2YTUxZjgyYjliZTYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.rkrbVYoIWdN7F7YClJu3vvA6WCns10in-SVKrHkR6d8"
}

response = requests.get(url, headers=headers)
# print(response) 
print(response.json())

{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg', 'genre_ids': [878, 28, 12], 'id': 969681, 'title': 'Spider-Man: Brand New Day', 'original_language': 'en', 'original_title': 'Spider-Man: Brand New Day', 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.", 'popularity': 710.812, 'poster_path': '/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg', 'release_date': '2026-07-29', 'softcore': False, 'video': False, 'vote_average': 7.865, 'vote_count': 2474}, {'adult': False, 'backdrop_path': '/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg', 'genre_ids': [12, 28, 14], 'id': 1368337, 'title': 'The Odyssey', 'original_language': 'en', 'original_title': 'The Odyssey', 'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.', 'popularity': 500.1532, 'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg', 'release_date': '2026-07-15', 'softcore': False, 'video': False, 'vote_average': 8.0, 'vote_count': 3519}, {'adult': False, 'backdrop_path': '/7GOW6jod9lLurW5utokAatxg7ql.jpg', 'genre_ids': [35, 12, 10751], 'id': 1204680, 'title': 'Coyote vs. Acme', 'original_language': 'en', 'original_title': 'Coyote vs. Acme', 'overview': 'After Acme products fail him one too many times in his dogged pursuit of the Roadrunner, Wile E. Coyote decides to hire a billboard lawyer to sue the Acme Corporation.', 'popularity': 637.0123, 'poster_path': '/orkLtdgMGiO9rTVMqJ1kKwrnup1.jpg', 'release_date': '2026-08-20', 'softcore': False, 'video': False, 'vote_average': 7.6, 'vote_count': 188}, {'adult': False, 'backdrop_path': '/qDa0fqDqIBCovRp975RvtGPcuN3.jpg', 'genre_ids': [28, 53], 'id': 1288445, 'title': 'Mutiny', 'original_language': 'en', 'original_title': 'Mutiny', 'overview': "After witnessing his billionaire boss' murder and being framed for the crime, Cole Reed boards a cargo ship on a one-man crusade to avenge his boss' death only to discover an international conspiracy.", 'popularity': 436.8093, 'poster_path': '/pu2VxGlpGwffOx292w18b1tv96j.jpg', 'release_date': '2026-08-19', 'softcore': False, 'video': False, 'vote_average': 6.4, 'vote_count': 306}, {'adult': False, 'backdrop_path': '/ziXF8wIBguHNCeplNthUlDTCZP8.jpg', 'genre_ids': [53, 28], 'id': 1386315, 'title': 'The Runner', 'original_language': 'en', 'original_title': 'The Runner', 'overview': 'Maia Marten, a brilliant London lawyer, has her life shattered by a single call on her morning run: her son has been taken. To get him back, she must keep running, obey every ruthless command, and trust no one-each second a test of how far a mother will go to save her child.', 'popularity': 325.554, 'poster_path': '/uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg', 'release_date': '2026-09-03', 'softcore': False, 'video': False, 'vote_average': 6.727, 'vote_count': 291}, {'adult': False, 'backdrop_path': '/yjK3ardrgdS8suZG8KMU82Q7U38.jpg', 'genre_ids': [10749], 'id': 1285366, 'title': 'Shape of My Heart', 'original_language': 'ja', 'original_title': '愛のぬくもり', 'overview': 'A romance about a man and a woman who, due to an unexpected event, end up switching bodies. Despite coming from completely different backgrounds and environments, the two try to overcome the various difficulties that arise from their body swap.', 'popularity': 241.3183, 'poster_path': '/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg', 'release_date': '2024-07-06', 'softcore': False, 'video': False, 'vote_average': 5.2, 'vote_count': 5}, {'adult': False, 'backdrop_path': '/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg', 'genre_ids': [28, 27, 878], 'id': 1375646, 'title': 'Colony', 'original_language': 'ko', 'original_title': '군체', 'overview': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.', 'popularity': 318.1829, 'poster_path': '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg', 'release_date': '2026-05-21', 'softcore': False, 'video': False, 'vote_average': 8.108, 'vote_count': 702}, {'adult': False, 'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg', 'genre_ids': [27, 53], 'id': 1339713, 'title': 'Obsession', 'original_language': 'en', 'original_title': 'Obsession', 'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.', 'popularity': 225.727, 'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg', 'release_date': '2026-05-13', 'softcore': False, 'video': False, 'vote_average': 8.199, 'vote_count': 5341}, {'adult': False, 'backdrop_path': '/zFCWfU2ViMIm38G1W8UsnSpqmWn.jpg', 'genre_ids': [10749, 18], 'id': 1516698, 'title': 'The Last Sunrise', 'original_language': 'en', 'original_title': 'The Last Sunrise', 'overview': "Ry, a college student with a chronic illness, escapes to Mallorca for the summer with her mother, where she unexpectedly falls for a local and begins to embrace living in the moment. But as her condition worsens and long-hidden family secrets come to light, everything she has found before summer's end is threatened.", 'popularity': 198.3803, 'poster_path': '/3PWJqDfygN0YNNjWsDUOXclCp3h.jpg', 'release_date': '2026-08-26', 'softcore': False, 'video': False, 'vote_average': 6.625, 'vote_count': 128}, {'adult': False, 'backdrop_path': '/tK3QdOOrX4qEkmSlvrmc8cK7iOU.jpg', 'genre_ids': [27, 35, 53], 'id': 1393326, 'title': 'Ghost in the Cell', 'original_language': 'id', 'original_title': 'Hantu Dalam Sel', 'overview': 'In a notorious prison, an invisible force begins killing inmates brutally, compelling enemy gangs and corrupt guards to work together as they try to survive the mounting bloodshed.', 'popularity': 227.3314, 'poster_path': '/zxcMdx0w5Zmg8yZuuiS7CJ8vOea.jpg', 'release_date': '2026-04-16', 'softcore': False, 'video': False, 'vote_average': 7.1, 'vote_count': 44}, {'adult': False, 'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg', 'genre_ids': [80, 28, 53], 'id': 1621552, 'title': 'Facing El Chapo', 'original_language': 'es', 'original_title': 'La captura', 'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.', 'popularity': 190.9893, 'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg', 'release_date': '2026-08-21', 'softcore': False, 'video': False, 'vote_average': 8.791, 'vote_count': 554}, {'adult': False, 'backdrop_path': '/tBZMwg5oCJn8P0pStfuOMhhSQD3.jpg', 'genre_ids': [10770, 10751, 878, 28, 35], 'id': 1506560, 'title': 'Clash of the Thundermans', 'original_language': 'en', 'original_title': 'Clash of the Thundermans', 'overview': 'When Chloe develops a destructive new superpower, the Hero League orders her to an elite boarding school for superheroes to learn control of her abilities. Faced with the prospect of sending Chloe away for years, the Thundermans split apart, with Phoebe, Barb and Billy taking her into hiding. Max, Hank, and Nora track their rogue family members, until the two factions face off against each other in a full-on battle for the Thundermans’ future.', 'popularity': 214.2234, 'poster_path': '/16oqRrWVzQm6qdGfBxvziZ2UiMT.jpg', 'release_date': '2026-09-03', 'softcore': False, 'video': False, 'vote_average': 6.895, 'vote_count': 19}, {'adult': False, 'backdrop_path': '/4gyx49ibwQslyrwuUS1c58PJEEd.jpg', 'genre_ids': [28, 35, 10752], 'id': 1137844, 'title': 'Mayday', 'original_language': 'en', 'original_title': 'Mayday', 'overview': 'When a U.S. Navy pilot on a top-secret mission during the Cold War gets trapped behind enemy lines, his only chance at survival is to form an alliance with an eccentric ex-KGB agent.', 'popularity': 226.6234, 'poster_path': '/7tlkTHxcTSlrPYURo0VuglaLPXv.jpg', 'release_date': '2026-09-03', 'softcore': False, 'video': False, 'vote_average': 7.978, 'vote_count': 228}, {'adult': False, 'backdrop_path': '/tBRSSfgqOAq7YlG8udcoJIBm2FG.jpg', 'genre_ids': [28, 80, 18], 'id': 1213243, 'title': 'Toxic: A Fairy Tale for Grown-ups', 'original_language': 'kn', 'original_title': 'ಟಾಕ್ಸಿಕ್', 'overview': 'A powerful drug cartel pulls the strings behind a facade of sun-soaked beaches as a gritty, violent underworld power struggle emerges during the crumbling of Portuguese colonial rule.', 'popularity': 165.9665, 'poster_path': '/oiIPU4lvnI0Ag2K9cyAi44eCaoE.jpg', 'release_date': '2026-08-26', 'softcore': False, 'video': False, 'vote_average': 8.0, 'vote_count': 69}, {'adult': False, 'backdrop_path': '/qjTqY5coNiz6sVtPng40IzltsoN.jpg', 'genre_ids': [16, 10751, 35, 12], 'id': 1084244, 'title': 'Toy Story 5', 'original_language': 'en', 'original_title': 'Toy Story 5', 'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.", 'popularity': 186.269, 'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg', 'release_date': '2026-06-17', 'softcore': False, 'video': False, 'vote_average': 8.347, 'vote_count': 2013}, {'adult': False, 'backdrop_path': '/xSJJQeAp9GBFmiKusysTRG6jQjt.jpg', 'genre_ids': [80, 18, 53], 'id': 860508, 'title': 'The Whisper Man', 'original_language': 'en', 'original_title': 'The Whisper Man', 'overview': 'When his young son vanishes, a widower enlists help from his estranged father, a retired detective who put away the serial killer now linked to the case.', 'popularity': 161.0316, 'poster_path': '/6UqflU8Qqkz7Dq4swJPqs0ZJjY4.jpg', 'release_date': '2026-08-27', 'softcore': False, 'video': False, 'vote_average': 6.803, 'vote_count': 485}, {'adult': False, 'backdrop_path': '/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg', 'genre_ids': [12, 16, 35, 10751, 14], 'id': 1315772, 'title': 'Minions & Monsters', 'original_language': 'en', 'original_title': 'Minions & Monsters', 'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.', 'popularity': 166.3452, 'poster_path': '/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg', 'release_date': '2026-06-24', 'softcore': False, 'video': False, 'vote_average': 7.576, 'vote_count': 1040}, {'adult': False, 'backdrop_path': '/lSd6nEnlaeQkswLLUgHC5gyuXyU.jpg', 'genre_ids': [28, 53, 27, 80], 'id': 1514682, 'title': 'Above & Below', 'original_language': 'en', 'original_title': 'Above & Below', 'overview': 'A group of friends set off for an unforgettable vacation. What begins as an adventure of partying and diving quickly turns into a nightmare when they are attacked by criminals in open waters.', 'popularity': 172.5457, 'poster_path': '/7bOuu1SRALGwsG2fLCTvRkCmQBj.jpg', 'release_date': '2026-07-29', 'softcore': False, 'video': False, 'vote_average': 6.25, 'vote_count': 24}, {'adult': False, 'backdrop_path': '/z7lZgL5tzefTfhyRtouThFhsuUS.jpg', 'genre_ids': [28, 878, 53], 'id': 1323244, 'title': 'Rage of Stars', 'original_language': 'en', 'original_title': 'Rage of Stars', 'overview': 'A story about a woman from the International Special Forces Unit, who has a premonition about the impending end of humanity.', 'popularity': 166.3505, 'poster_path': '/oLld47ZT1I3iecM3OWhIphohQUJ.jpg', 'release_date': '2026-08-06', 'softcore': False, 'video': False, 'vote_average': 5.968, 'vote_count': 77}, {'adult': False, 'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg', 'genre_ids': [10751, 14, 35, 12], 'id': 1108427, 'title': 'Moana', 'original_language': 'en', 'original_title': 'Moana', 'overview': "Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.", 'popularity': 162.8374, 'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg', 'release_date': '2026-07-08', 'softcore': False, 'video': False, 'vote_average': 6.199, 'vote_count': 261}], 'total_pages': 58798, 'total_results': 1175951}

In [ ]:
url = "https://api.themoviedb.org/3/discover/movie"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyZDM3YWE2YjNkZDI3MDMyNzZhODc5Yzk5ZmYwZThmYSIsIm5iZiI6MTc4ODQyMDI1OS4xNzI5OTk5LCJzdWIiOiI2YTk5MjBhM2JkOTk2YTUxZjgyYjliZTYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.rkrbVYoIWdN7F7YClJu3vvA6WCns10in-SVKrHkR6d8"
    }

query_params = {
    "include_adult": "false",
    "include_video": "false",
    "language": "en-US",
    "page": 1,
    "sort_by": "popularity.desc"
}

max_pages = 500 
all_movies = []

for page in range(1, max_pages + 1):
    query_params["page"] = page
    response = requests.get(url, headers=headers, params=query_params)
    # print(response)
    if response.status_code == 200:
        data = response.json()
        movies_on_page = data.get("results", [])
        all_movies.extend(movies_on_page)
        
        # Stop early if the API reports there are no more pages
        if page >= data.get("total_pages", 1) or page >= 500:
            break
            
        time.sleep(0.2)  # Polite pause between requests
    else:
        print(f"Failed to fetch page {page}. Status code: {response.status_code}")
        print(response.text)
        break

# Convert the combined list into a Pandas DataFrame
df = pd.DataFrame(all_movies)

print(f"\nSuccessfully collected {len(df)} movies!")
if not df.empty:
    print(df.head())  # View the first 5 rows

Successfully collected 10000 movies!
   adult                     backdrop_path        genre_ids       id  \
0  False  /qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg    [878, 28, 12]   969681
1  False   /RMXG8myu1aGlNUsRjtxzmpdMK0.jpg     [12, 28, 14]  1368337
2  False  /l9mFW9HQnAZ4r1ChZJHoOT3jaal.jpg  [35, 12, 10751]  1204680
3  False  /qDa0fqDqIBCovRp975RvtGPcuN3.jpg         [28, 53]  1288445
4  False  /ziXF8wIBguHNCeplNthUlDTCZP8.jpg         [53, 28]  1386315

                       title original_language             original_title  \
0  Spider-Man: Brand New Day                en  Spider-Man: Brand New Day
1                The Odyssey                en                The Odyssey
2            Coyote vs. Acme                en            Coyote vs. Acme
3                     Mutiny                en                     Mutiny
4                 The Runner                en                 The Runner

                                            overview  popularity  \
0  Fighting crime full-time as Spider-Man in a wo...    710.8120
1  Odysseus, the legendary King of Ithaca, embark...    500.1532
2  After Acme products fail him one too many time...    637.0123
3  After witnessing his billionaire boss' murder ...    436.8093
4  Maia Marten, a brilliant London lawyer, has he...    325.5540

                        poster_path release_date  softcore  video  \
0  /bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg   2026-07-29     False  False
1  /5rhTDKUhPYvpdQIijFIs5VoWsON.jpg   2026-07-15     False  False
2  /orkLtdgMGiO9rTVMqJ1kKwrnup1.jpg   2026-08-20     False  False
3  /pu2VxGlpGwffOx292w18b1tv96j.jpg   2026-08-19     False  False
4  /uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg   2026-09-03     False  False

   vote_average  vote_count
0         7.867        2482
1         8.001        3523
2         7.629         194
3         6.370         307
4         6.700         299

In [26]:
df.head(5)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,710.8120,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.867,2482
1,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",500.1532,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,8.001,3523
2,False,/l9mFW9HQnAZ4r1ChZJHoOT3jaal.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,637.0123,/orkLtdgMGiO9rTVMqJ1kKwrnup1.jpg,2026-08-20,False,False,7.629,194
3,False,/qDa0fqDqIBCovRp975RvtGPcuN3.jpg,"[28, 53]",1288445,Mutiny,en,Mutiny,After witnessing his billionaire boss' murder ...,436.8093,/pu2VxGlpGwffOx292w18b1tv96j.jpg,2026-08-19,False,False,6.370,307
4,False,/ziXF8wIBguHNCeplNthUlDTCZP8.jpg,"[53, 28]",1386315,The Runner,en,The Runner,"Maia Marten, a brilliant London lawyer, has he...",325.5540,/uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg,2026-09-03,False,False,6.700,299

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              10000 non-null  bool
 1   backdrop_path      9227 non-null   str
 2   genre_ids          10000 non-null  object
 3   id                 10000 non-null  int64
 4   title              10000 non-null  str
 5   original_language  10000 non-null  str
 6   original_title     10000 non-null  str
 7   overview           10000 non-null  str
 8   popularity         10000 non-null  float64
 9   poster_path        9827 non-null   str
 10  release_date       10000 non-null  str
 11  softcore           10000 non-null  bool
 12  video              10000 non-null  bool
 13  vote_average       10000 non-null  float64
 14  vote_count         10000 non-null  int64
dtypes: bool(3), float64(2), int64(2), object(1), str(7)
memory usage: 966.9+ KB